--- # LOOP PLAYBOOK EXAMPLE
- hosts: apacheweb
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
   - name: Run the uptime command on all hosts and log it
     user: name={{ item }} state=present
     with_itesm: 
       - user1       
       - user2       
       - user3       
